
import type { Product, User, Order, Review, Notification } from '@/types';

export const categories = [
    { name: 'Burger', hint: 'burger' },
    { name: 'Pizza', hint: 'pizza' },
    { name: 'Biryani', hint: 'biryani' },
    { name: 'Kebab', hint: 'kebab' },
    { name: 'Set Menu', hint: 'rice meal' },
    { name: 'Pasta', hint: 'pasta' },
    { name: 'Soup', hint: 'soup' },
    { name: 'Salad', hint: 'salad' },
    { name: 'Dessert', hint: 'cake' },
    { name: 'Drinks', hint: 'drinks' },
    { name: 'Curry', hint: 'curry' },
    { name: 'Rice', hint: 'rice' },
    { name: 'Noodles', hint: 'noodles' },
    { name: 'Seafood', hint: 'seafood' },
    { name: 'Vegetarian', hint: 'vegetarian' },
    { name: 'Sandwich', hint: 'sandwich' },
    { name: 'Breakfast', hint: 'breakfast' },
    { name: 'Appetizers', hint: 'appetizers' },
    { name: 'Coffee', hint: 'coffee' },
    { name: 'Ice Cream', hint: 'ice cream' },
];

export const users: User[] = [
  { 
    id: 'seller1', 
    name: 'Burger Queen', 
    email: 'seller1@test.com', 
    role: 'seller', 
    avatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391393/avatar1_b1wt3x.png',
    shopName: 'Burger Queen',
    shopAddress: '123 Burger Lane, Rangpur',
    zone: 'inside-rangpur-city',
    planType: 'pro',
    productUploadCount: 8,
  },
  { 
    id: 'seller2', 
    name: 'Pizza King', 
    email: 'seller2@test.com', 
    role: 'seller', 
    avatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391393/avatar2_y9kzqs.png',
    shopName: 'Pizza King',
    shopAddress: '456 Pizza Street, Rangpur',
    zone: 'rangpur-division',
    planType: 'free',
    productUploadCount: 4,
  },
  { id: 'buyer1', name: 'Aisha Ahmed', email: 'buyer1@test.com', role: 'buyer', avatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391394/avatar3_h3g5ar.png' },
  { id: 'buyer2', name: 'Rahim Khan', email: 'buyer2@test.com', role: 'buyer', avatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391394/avatar4_b3jd8q.png' },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'Classic Beef Burger',
    description: 'A juicy beef patty with fresh lettuce, tomato, onions, and our secret sauce, all in a toasted brioche bun.',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391392/burger1_cohr5o.png'],
    category: 'Burger',
    rating: 4.5,
    price: 350,
    sellerId: 'seller1',
    deliveryTime: '20-30 mins',
    commissionPercentage: 5,
    tags: ['Best Value'],
  },
  {
    id: 'prod2',
    name: 'Spicy Chicken Burger',
    description: 'Crispy fried chicken breast with a spicy kick, pickles, and mayo. Not for the faint of heart!',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391392/burger2_pnh0kj.png'],
    category: 'Burger',
    rating: 4.8,
    price: 380,
    originalPrice: 420,
    sellerId: 'seller1',
    deliveryTime: '25-35 mins',
    commissionPercentage: 7,
    tags: ['Spicy', 'New'],
  },
  {
    id: 'prod3',
    name: 'Margherita Pizza',
    description: 'The classic pizza with fresh mozzarella, basil, and a rich tomato sauce on a thin crust.',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391393/pizza1_kchjpf.png'],
    category: 'Pizza',
    rating: 4.2,
    price: 650,
    sellerId: 'seller2',
    deliveryTime: '30-45 mins',
    commissionPercentage: 10,
  },
  {
    id: 'prod4',
    name: 'Pepperoni Pizza',
    description: 'A crowd-pleaser. Generous amounts of pepperoni and mozzarella cheese.',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391393/pizza2_k1sctj.png'],
    category: 'Pizza',
    rating: 4.6,
    price: 750,
    originalPrice: 850,
    sellerId: 'seller2',
    deliveryTime: '30-45 mins',
    commissionPercentage: 10,
    tags: ['Best Value'],
  },
  {
    id: 'prod5',
    name: 'Cola',
    description: 'A refreshing can of cola to quench your thirst.',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391392/drink1_g6qjrm.png'],
    category: 'Drinks',
    rating: 5,
    price: 40,
    sellerId: 'seller1',
    deliveryTime: '5-10 mins',
    commissionPercentage: 5,
  },
  {
    id: 'prod6',
    name: 'Lemonade',
    description: 'Freshly squeezed lemonade, the perfect balance of sweet and tart.',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391392/drink2_tqjcvw.png'],
    category: 'Drinks',
    rating: 4.7,
    price: 80,
    sellerId: 'seller2',
    deliveryTime: '10-15 mins',
    commissionPercentage: 5,
  },
  {
    id: 'prod7',
    name: 'Chocolate Lava Cake',
    description: 'Warm, gooey chocolate cake with a molten center. Served with a scoop of vanilla ice cream.',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391392/dessert1_gq4gsh.png'],
    category: 'Dessert',
    rating: 4.9,
    price: 250,
    sellerId: 'seller1',
    deliveryTime: '15-20 mins',
    commissionPercentage: 7,
    tags: ['New'],
  },
    {
    id: 'prod8',
    name: 'Veggie Burger',
    description: 'A delicious and hearty vegetarian patty with all the classic fixings. A healthy choice!',
    images: ['https://res.cloudinary.com/drewes4b7/image/upload/v1717391392/burger3_i6lqwh.png'],
    category: 'Burger',
    rating: 4.3,
    price: 320,
    sellerId: 'seller1',
    deliveryTime: '20-30 mins',
    commissionPercentage: 5,
  },
];

export const reviews: Review[] = [
  {
    id: 'review1',
    productId: 'prod1',
    userId: 'buyer1',
    userName: 'Aisha Ahmed',
    userAvatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391394/avatar3_h3g5ar.png',
    rating: 5,
    comment: 'Absolutely the best burger in town! The patty was cooked to perfection. Will definitely order again.',
    createdAt: new Date('2024-05-20T14:30:00Z'),
  },
  {
    id: 'review2',
    productId: 'prod1',
    userId: 'buyer2',
    userName: 'Rahim Khan',
    userAvatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391394/avatar4_b3jd8q.png',
    rating: 4,
    comment: 'Very good burger, but the bun was a little soggy. The sauce is amazing though!',
    createdAt: new Date('2024-05-18T19:00:00Z'),
  },
  {
    id: 'review3',
    productId: 'prod3',
    userId: 'buyer1',
    userName: 'Aisha Ahmed',
    userAvatar: 'https://res.cloudinary.com/drewes4b7/image/upload/v1717391394/avatar3_h3g5ar.png',
    rating: 4,
    comment: 'Good classic Margherita. The basil was fresh and fragrant. Crust could be a bit crispier.',
    createdAt: new Date('2024-05-15T12:00:00Z'),
  },
];


export const orders: Order[] = [
  // This data is now primarily managed by Firestore, but kept for reference/testing
];

export const notifications: Notification[] = [
    // This data is now primarily managed by Firestore, but kept for reference/testing
]
